# Generated by Django 5.2.1 on 2025-05-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichatbot', '0003_remove_chats_chats_remove_chats_user_chatsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='token_count',
        ),
    ]
