# Generated by Django 5.2 on 2025-05-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichatbot', '0005_alter_chatmessage_options_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
