# Generated by Django 5.2.1 on 2025-05-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_balance_balance_balance_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
